### ISSUE TITLE
Constant error "backend token is not valid"

### ISSUE THREAD

**Issue by octoshrimpy** [ReceiptManager/receipt-manager-webapp#54]
```Backend token not set, invalid or expired. Check settings or try to clear browser cache!```

How to fix? The default config does not have an empty value for `backendToken`, and adding one doesn't seem to do anything. Is this for the parser server? or for the backend of the webapp?

**Comment by Dielee** [comment]
Where do your get this error ?

**Comment by octoshrimpy** [comment]
The error comes up as a red bar on the bottom of the webapp page.

**Comment by Dielee** [comment]
Please show me your `/webroot/settings/settings.json` file

**Comment by caco3** [comment]
I have the same issue.
The setup seems not to work as documented.
Like I need to start it with `docker run -d --network host --name "receipt-manager-webapp" -e backendIP="192.168.1.160" -v ***/config:/app/config -v ***/webroot:/app/webroot -e backendPort="5558" -e useSSL="false" dielee/receipt-manager-webapp:latest` to get it up at all. (Note the webroot volume).

But then it runs into a missing mysql DB:
```
192.168.1.160 - - [2023-11-28 21:03:09] "GET /api/getBackendConfig?token=d644b094-2e0b-49ce-b3b8-7d01a3286302 HTTP/1.1" 200 608 0.001024
[2023-11-28 21:03:09,615] ERROR in app: Exception on /api/getValue [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 506, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Table 'receiptData.stores' doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/app/src/api.py", line 277, in get_categories
    ret_json = get_data_from_db(get_values_from)
  File "/app/src/util.py", line 401, in get_data_from_db
    cur.execute(sql_select)
  File "/usr/local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 510, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'receiptData.stores' doesn't exist
192.168.1.160 - - [2023-11-28 21:03:09] "GET /api/getValue?token=d644b094-2e0b-49ce-b3b8-7d01a3286302&getValuesFrom=stores HTTP/1.1" 500 490 0.018408
[2023-11-28 21:03:09,628] ERROR in app: Exception on /api/getValue [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 506, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Table 'receiptData.categories' doesn't exist
```

Do I need to setup the table myself? There is no documentation for this!
